import turtle
turtle.color('#2e66ff','white')
turtle.width(3)
turtle.begin_fill()
for a in range(88):
    turtle.fd(3)
    turtle.rt(1)
turtle.color('#2e66ff',"#ffb6ec")
turtle.begin_fill()
for a in range(182):
    turtle.fd(3)
    turtle.rt(1)
turtle.end_fill()
for a in range(90):
    turtle.fd(3)
    turtle.rt(1)

turtle.rt(90)
turtle.pu()
turtle.fd(57.32484076433121*3)
turtle.rt(90)
turtle.fd(57.32484076433121*3)
turtle.rt(180)
turtle.pd()


turtle.color('#2e66ff',"white")
turtle.begin_fill()
for b in range(60*3):
    turtle.rt(1+b/30)
    turtle.fd(1)
    turtle.setheading(0)
for c in range(175):
    turtle.lt(1+b/30)
    turtle.fd(1)
    turtle.setheading(0)
turtle.end_fill()
turtle.pu()
turtle.rt(180)
turtle.fd(160)
turtle.lt(90)
turtle.fd(19)
turtle.rt(150)
turtle.color('#2e66ff',"#ffb6ec")
turtle.pd()
turtle.begin_fill()
for a in range(228):
    turtle.fd(1)
    turtle.rt(1)
turtle.end_fill()
turtle.pu()
turtle.setheading(180)
turtle.fd(250)
turtle.color('#2e66ff',"#fff152")
turtle.pd()
turtle.begin_fill()
turtle.setheading(120)
for a in range(250):
    turtle.fd(1)
    turtle.rt(1)
turtle.end_fill()
turtle.setheading(180)
turtle.pu()
turtle.fd(120)
turtle.lt(90)
turtle.fd(20)
turtle.color('#fff152',"#ffb6ec")
turtle.pd()
turtle.setheading(280)
turtle.width(5)
for a in range(30):
    turtle.fd(3)
    turtle.lt(1)
turtle.pu()
for a in range(20):
    turtle.fd(3)
    turtle.lt(1)
turtle.pd()
for a in range(2):
    turtle.fd(3)
    turtle.lt(1)
turtle.done()
